approve_by_comment: true
approve_regex: '^(Approved|lgtm|LGTM|:shipit:|:star:|:+1:|:ship:)'
reject_regex: '^(Rejected|:-1:)'
reset_on_push: false
reviewers:
  members:
  - ashwanthkumar
  - manojlds
  - sriram-r
  name: default
  required: 2

